// Code generated by internal/gen/manifest2go from contract/api-manifest.json (revision 7, schemaHash b60e77ffcbf08d985a993dbdbd4cf610f12f7c7e70f090aee5ff8d523f70bb57, manifest SHA256 f6255bc868b4de5cb2af759a55069ab4651027d4125ef86d37f14a91d3307288). DO NOT EDIT.

package api

// ManifestRevision is the manifest revision locked at build time. It is compared with the response
// header tansr-manifest-revision for diagnostics only; the client never switches logic on it.
const ManifestRevision = 7

// ManifestSchemaHash is the aggregate schemaHash locked at build time (compared with the `sha256:` part
// of tansr-schema-hash on discovery responses).
const ManifestSchemaHash = "b60e77ffcbf08d985a993dbdbd4cf610f12f7c7e70f090aee5ff8d523f70bb57"

// ManifestSourceSHA256 is the SHA256 of the manifest file the table was generated from.
const ManifestSourceSHA256 = "f6255bc868b4de5cb2af759a55069ab4651027d4125ef86d37f14a91d3307288"

// Domains is the accepting-domain vocabulary (= response header tansr-domain), derived from the operation table.
var Domains = []string{"discovery", "session", "execution", "archive", "archive-sync", "cache", "terminal", "terminal-observation", "terminal-profile"}

// Families is the contract-family vocabulary (facade operations have no family and are not listed).
var Families = []string{"agent-session-v1", "sdk2-ext-v1", "sdk2-archive-recovery-v1", "archive-sync-v1", "sdk2-cache-v1", "sdk2-cache-core-v1", "terminal-services-v1", "terminal-observation-v1", "terminal-profile-v1"}

// FamilyRequestIDPaths is the body key path of the client idempotency key per registered family
// (manifest families[].requestIdPath, revision 7): the position Idempotency-Key is mapped to by the server;
// nil = the family's body has no such position (deduplication by request fingerprint only).
var FamilyRequestIDPaths = map[string][]string{
	"agent-session-v1":          nil,
	"sdk2-ext-v1":               []string{"request", "requestId"},
	"sdk2-archive-recovery-v1":  []string{"request", "requestId"},
	"archive-sync-v1":           nil,
	"sdk2-cache-v1":             []string{"request", "requestId"},
	"sdk2-cache-core-v1":        []string{"request", "requestId"},
	"terminal-services-v1":      []string{"requestId"},
	"terminal-observation-v1":   []string{"requestId"},
	"terminal-profile-v1":       []string{"requestId"},
	"terminal-shell-sandbox-v1": nil,
	"unified-v1":                nil,
}

// Operation names.
const (
	OpDiscoveryManifest               = "discovery.manifest"
	OpDiscoveryCapabilities           = "discovery.capabilities"
	OpDiscoverySessionCapabilities    = "discovery.session.capabilities"
	OpSessionCapabilities             = "session.capabilities"
	OpSessionCreate                   = "session.create"
	OpSessionList                     = "session.list"
	OpSessionGet                      = "session.get"
	OpSessionClose                    = "session.close"
	OpSessionMessageSend              = "session.message.send"
	OpSessionEventsObserve            = "session.events.observe"
	OpSessionInterrupt                = "session.interrupt"
	OpSessionHistoryRead              = "session.history.read"
	OpSessionToolResult               = "session.tool.result"
	OpSessionPermissionDecide         = "session.permission.decide"
	OpSessionQuestionAnswer           = "session.question.answer"
	OpSessionCompact                  = "session.compact"
	OpSessionCheckpointList           = "session.checkpoint.list"
	OpSessionCheckpointCreate         = "session.checkpoint.create"
	OpSessionCheckpointImport         = "session.checkpoint.import"
	OpSessionCheckpointRestore        = "session.checkpoint.restore"
	OpSessionCheckpointExport         = "session.checkpoint.export"
	OpSessionCheckpointDelete         = "session.checkpoint.delete"
	OpSessionCwdSet                   = "session.cwd.set"
	OpSessionAudioTranscribe          = "session.audio.transcribe"
	OpSessionAudioSpeak               = "session.audio.speak"
	OpSessionInputCapabilities        = "session.input.capabilities"
	OpSessionInputSubmit              = "session.input.submit"
	OpSessionInputStatus              = "session.input.status"
	OpApprovalCredentialSubmit        = "approval.credential.submit"
	OpExecutionInitialize             = "execution.initialize"
	OpExecutionCapabilities           = "execution.capabilities"
	OpExecutionBoundary               = "execution.boundary"
	OpExecutionBindingCreate          = "execution.binding.create"
	OpExecutionStatus                 = "execution.status"
	OpExecutorRegister                = "executor.register"
	OpExecutorHeartbeat               = "executor.heartbeat"
	OpExecutorOperationsPoll          = "executor.operations.poll"
	OpExecutorReceiptSubmit           = "executor.receipt.submit"
	OpArchiveCapabilities             = "archive.capabilities"
	OpArchiveBindingTarget            = "archive.binding.target"
	OpArchiveBindingCreate            = "archive.binding.create"
	OpArchiveBindingGet               = "archive.binding.get"
	OpArchiveBindingClose             = "archive.binding.close"
	OpArchiveStatus                   = "archive.status"
	OpArchiveEventsObserve            = "archive.events.observe"
	OpArchiveRecordsRead              = "archive.records.read"
	OpArchiveArtifactRead             = "archive.artifact.read"
	OpArchiveAckCommit                = "archive.ack.commit"
	OpArchiveAckRebase                = "archive.ack.rebase"
	OpArchiveOperationQuery           = "archive.operation.query"
	OpArchiveSync                     = "archive.sync"
	OpMaterialResponseSubmit          = "material.response.submit"
	OpMaterialStatus                  = "material.status"
	OpMaterialUploadStatus            = "material.upload.status"
	OpMaterialUploadChunk             = "material.upload.chunk"
	OpCacheCapabilities               = "cache.capabilities"
	OpCacheBindingOpen                = "cache.binding.open"
	OpCacheBindingGet                 = "cache.binding.get"
	OpCacheBindingRenew               = "cache.binding.renew"
	OpCacheBindingRebind              = "cache.binding.rebind"
	OpCacheBindingRotate              = "cache.binding.rotate"
	OpCacheBindingClose               = "cache.binding.close"
	OpCacheOperationQuery             = "cache.operation.query"
	OpCacheDiagnostics                = "cache.diagnostics"
	OpCacheCoreDiagnostics            = "cache.core.diagnostics"
	OpTerminalCapabilities            = "terminal.capabilities"
	OpTerminalBindingCreate           = "terminal.binding.create"
	OpTerminalExecutorEventsObserve   = "terminal.executor.events.observe"
	OpTerminalOutputBatch             = "terminal.output.batch"
	OpTerminalExecutionState          = "terminal.execution.state"
	OpTerminalOutputObserve           = "terminal.output.observe"
	OpTerminalOutputStatus            = "terminal.output.status"
	OpTerminalConfigurationRead       = "terminal.configuration.read"
	OpTerminalConfigurationCommit     = "terminal.configuration.commit"
	OpTerminalMemoryRead              = "terminal.memory.read"
	OpTerminalMemoryCommand           = "terminal.memory.command"
	OpTerminalMemoryReceipt           = "terminal.memory.receipt"
	OpTerminalObservationResources    = "terminal.observation.resources"
	OpTerminalObservationCorrelations = "terminal.observation.correlations"
	OpTerminalProfileCatalog          = "terminal.profile.catalog"
	OpTerminalProfileUsage            = "terminal.profile.usage"
)

// operations is the operation table (manifest operations[] verbatim): Path is the /api template that the
// client always instantiates locally, Params the placeholder sequence, Aliases the session-scoped alias
// templates of the same operation and Query the whitelist of allowed query keys.
var operations = []Operation{
	{Name: OpDiscoveryManifest, Method: "GET", Path: "/api/manifest", Params: nil, Aliases: nil, Domain: "discovery", Family: "", Kind: "read", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpDiscoveryCapabilities, Method: "GET", Path: "/api/capabilities", Params: nil, Aliases: nil, Domain: "discovery", Family: "", Kind: "read", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpDiscoverySessionCapabilities, Method: "GET", Path: "/api/sessions/:id/capabilities", Params: []string{"id"}, Aliases: nil, Domain: "discovery", Family: "", Kind: "read", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCapabilities, Method: "GET", Path: "/api/capabilities/sessions", Params: nil, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCreate, Method: "POST", Path: "/api/sessions", Params: nil, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#CreateSessionBodySchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionList, Method: "GET", Path: "/api/sessions", Params: nil, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: []string{"limit", "offset"}, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionGet, Method: "GET", Path: "/api/sessions/:id", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: []string{"include"}, Request: "", Response: "agent-session-v1#V2SessionMetaView", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionClose, Method: "DELETE", Path: "/api/sessions/:id", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionMessageSend, Method: "POST", Path: "/api/sessions/:id/messages", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#MessagesBodySchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionEventsObserve, Method: "GET", Path: "/api/sessions/:id/events", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "stream", SSE: true, Query: []string{"exclude"}, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionInterrupt, Method: "POST", Path: "/api/sessions/:id/interrupt", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionHistoryRead, Method: "GET", Path: "/api/sessions/:id/history", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: []string{"offset", "limit"}, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionToolResult, Method: "POST", Path: "/api/sessions/:id/tool-results/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#ToolResultReceiptSchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionPermissionDecide, Method: "POST", Path: "/api/sessions/:id/permission/:ticketId", Params: []string{"id", "ticketId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#PermissionReceiptSchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionQuestionAnswer, Method: "POST", Path: "/api/sessions/:id/questions/:ticketId", Params: []string{"id", "ticketId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#QuestionReceiptSchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCompact, Method: "POST", Path: "/api/sessions/:id/compact", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#CompactBodySchema", Response: "agent-session-v1#V2CompactResult", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointList, Method: "GET", Path: "/api/sessions/:id/checkpoints", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: nil, Request: "", Response: "agent-session-v1#V2CheckpointList", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointCreate, Method: "POST", Path: "/api/sessions/:id/checkpoints", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#CheckpointBodySchema", Response: "agent-session-v1#V2CheckpointMeta", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointImport, Method: "POST", Path: "/api/sessions/:id/checkpoints/import", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: []string{"label"}, Request: "", Response: "agent-session-v1#V2CheckpointMeta", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointRestore, Method: "POST", Path: "/api/sessions/:id/checkpoints/:targetId/restore", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#RestoreBodySchema", Response: "agent-session-v1#V2RestoreResult", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointExport, Method: "GET", Path: "/api/sessions/:id/checkpoints/:targetId/export", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCheckpointDelete, Method: "DELETE", Path: "/api/sessions/:id/checkpoints/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionCwdSet, Method: "POST", Path: "/api/sessions/:id/cwd", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#SetCwdBodySchema", Response: "agent-session-v1#V2SetCwdResult", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionAudioTranscribe, Method: "POST", Path: "/api/sessions/:id/audio/transcriptions", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#AudioTranscriptionsBodySchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionAudioSpeak, Method: "POST", Path: "/api/sessions/:id/audio/speech", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#AudioSpeechBodySchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionInputCapabilities, Method: "GET", Path: "/api/sessions/:id/input-capabilities", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionInputSubmit, Method: "POST", Path: "/api/sessions/:id/inputs", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "agent-session-v1#SubmitInputBodySchema", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpSessionInputStatus, Method: "GET", Path: "/api/sessions/:id/inputs/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "read", SSE: false, Query: []string{"historyEpoch", "turnId"}, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpApprovalCredentialSubmit, Method: "POST", Path: "/api/approvals/:id/credential", Params: []string{"id"}, Aliases: nil, Domain: "session", Family: "agent-session-v1", Kind: "write", SSE: false, Query: nil, Request: "", Response: "", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutionInitialize, Method: "POST", Path: "/api/sessions/:id/initialize", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#SessionInitializeRequest", Response: "sdk2-ext-v1#SessionExecutionCapabilities", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutionCapabilities, Method: "GET", Path: "/api/sessions/:id/execution-capabilities", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#SessionExecutionCapabilities", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutionBoundary, Method: "GET", Path: "/api/sessions/:id/execution-boundary", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#ExecutionBoundary", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutionBindingCreate, Method: "POST", Path: "/api/sessions/:id/execution-bindings", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#ExecutionBindingRequest", Response: "sdk2-ext-v1#SessionExecutionCapabilities", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutionStatus, Method: "GET", Path: "/api/sessions/:id/executions/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#ExecutionStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutorRegister, Method: "POST", Path: "/api/executors/connections", Params: nil, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#ExecutorRegistrationRequest", Response: "sdk2-ext-v1#ExecutorConnection", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutorHeartbeat, Method: "POST", Path: "/api/executors/:id/heartbeats", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#ExecutorHeartbeatRequest", Response: "sdk2-ext-v1#ExecutorConnection", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutorOperationsPoll, Method: "GET", Path: "/api/executors/:id/operations", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol", "connectionId"}, Request: "", Response: "sdk2-ext-v1#ExecutionBatch", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpExecutorReceiptSubmit, Method: "POST", Path: "/api/executors/:id/receipts", Params: []string{"id"}, Aliases: nil, Domain: "execution", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#ExecutionReceiptRequest", Response: "sdk2-ext-v1#ExecutionStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveCapabilities, Method: "GET", Path: "/api/capabilities/archive", Params: nil, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: nil, Request: "", Response: "sdk2-ext-v1#CapabilitiesResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveBindingTarget, Method: "GET", Path: "/api/sessions/:id/binding-target", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "sdk2-ext-v1#BindingTargetRequest", Response: "sdk2-ext-v1#BindingTargetView", ETagPath: []string{"revision"}, ExpectedRevision: nil},
	{Name: OpArchiveBindingCreate, Method: "POST", Path: "/api/archive/bindings", Params: nil, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#BindingCreateRequest", Response: "sdk2-ext-v1#BindingView", ETagPath: []string{"revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpArchiveBindingGet, Method: "GET", Path: "/api/archive/bindings/:id", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#BindingView", ETagPath: []string{"revision"}, ExpectedRevision: nil},
	{Name: OpArchiveBindingClose, Method: "POST", Path: "/api/archive/bindings/:id/close", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#BindingCloseRequest", Response: "sdk2-ext-v1#MutationReceipt", ETagPath: []string{"revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpArchiveStatus, Method: "GET", Path: "/api/archive/bindings/:id/archive/status", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#ArchiveStatus", ETagPath: []string{"revision"}, ExpectedRevision: nil},
	{Name: OpArchiveEventsObserve, Method: "GET", Path: "/api/archive/bindings/:id/events", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "stream", SSE: true, Query: []string{"protocol"}, Request: "", Response: "sdk2-ext-v1#EventFrame", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveRecordsRead, Method: "GET", Path: "/api/archive/bindings/:id/archive/records", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol", "historyEpoch", "deletionGeneration", "projectionRevision", "limit", "maxBytes", "afterSequence"}, Request: "sdk2-ext-v1#ArchiveReadRequest", Response: "sdk2-ext-v1#ArchivePage", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveArtifactRead, Method: "GET", Path: "/api/archive/bindings/:id/archive/artifacts/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol", "historyEpoch", "deletionGeneration", "projectionRevision", "offset", "maxBytes"}, Request: "sdk2-ext-v1#ArtifactReadRequest", Response: "sdk2-ext-v1#ArtifactChunk", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveAckCommit, Method: "POST", Path: "/api/archive/bindings/:id/archive/acks", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#ArchiveAckRequest", Response: "sdk2-ext-v1#MutationReceipt", ETagPath: []string{"revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpArchiveAckRebase, Method: "POST", Path: "/api/archive/bindings/:id/archive/ack-rebases", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-archive-recovery-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-archive-recovery-v1#AckRebaseRequest", Response: "sdk2-archive-recovery-v1#AckRebaseReceipt", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveOperationQuery, Method: "GET", Path: "/api/archive/operations", Params: nil, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol", "operation", "operationEpoch", "requestId", "bindingId", "sessionId"}, Request: "sdk2-ext-v1#OperationStatusRequest", Response: "sdk2-ext-v1#MutationReceipt", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpArchiveSync, Method: "POST", Path: "/api/archive/sync/:id", Params: []string{"id"}, Aliases: nil, Domain: "archive-sync", Family: "archive-sync-v1", Kind: "write", SSE: false, Query: nil, Request: "archive-sync-v1#Request", Response: "archive-sync-v1#Response", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpMaterialResponseSubmit, Method: "POST", Path: "/api/archive/bindings/:id/material-responses", Params: []string{"id"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#MaterialResponseRequest", Response: "sdk2-ext-v1#MaterialReceipt", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpMaterialStatus, Method: "GET", Path: "/api/archive/bindings/:id/materials/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "sdk2-ext-v1#MaterialStatusRequest", Response: "sdk2-ext-v1#MaterialReceipt", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpMaterialUploadStatus, Method: "GET", Path: "/api/archive/bindings/:id/materials/:targetId/uploads/:uploadId", Params: []string{"id", "targetId", "uploadId"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "sdk2-ext-v1#MaterialUploadStatusRequest", Response: "sdk2-ext-v1#MaterialUploadStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpMaterialUploadChunk, Method: "POST", Path: "/api/archive/bindings/:id/materials/:targetId/uploads/:uploadId/chunks", Params: []string{"id", "targetId", "uploadId"}, Aliases: nil, Domain: "archive", Family: "sdk2-ext-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-ext-v1#MaterialUploadChunkRequest", Response: "sdk2-ext-v1#MaterialUploadStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpCacheCapabilities, Method: "GET", Path: "/api/capabilities/cache", Params: nil, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "read", SSE: false, Query: nil, Request: "", Response: "sdk2-cache-v1#CapabilitiesResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpCacheBindingOpen, Method: "POST", Path: "/api/cache/bindings", Params: nil, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-cache-v1#OpenRequest", Response: "sdk2-cache-v1#OpenResponse", ETagPath: []string{"binding", "revision"}, ExpectedRevision: nil},
	{Name: OpCacheBindingGet, Method: "GET", Path: "/api/cache/bindings/:id", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "read", SSE: false, Query: []string{"protocol"}, Request: "sdk2-cache-v1#BindingQuery", Response: "sdk2-cache-v1#BindingView", ETagPath: []string{"revision"}, ExpectedRevision: nil},
	{Name: OpCacheBindingRenew, Method: "POST", Path: "/api/cache/bindings/:id/renew", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-cache-v1#RenewRequest", Response: "sdk2-cache-v1#MutationReceipt", ETagPath: []string{"binding", "revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpCacheBindingRebind, Method: "POST", Path: "/api/cache/bindings/:id/rebind", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-cache-v1#RebindRequest", Response: "sdk2-cache-v1#MutationReceipt", ETagPath: []string{"binding", "revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpCacheBindingRotate, Method: "POST", Path: "/api/cache/bindings/:id/rotate", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-cache-v1#RotateRequest", Response: "sdk2-cache-v1#MutationReceipt", ETagPath: []string{"binding", "revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpCacheBindingClose, Method: "POST", Path: "/api/cache/bindings/:id/close", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "write", SSE: false, Query: nil, Request: "sdk2-cache-v1#CloseRequest", Response: "sdk2-cache-v1#MutationReceipt", ETagPath: []string{"binding", "revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpCacheOperationQuery, Method: "GET", Path: "/api/cache/operations", Params: nil, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "read", SSE: false, Query: []string{"protocol", "operation", "operationEpoch", "requestId", "bindingId"}, Request: "sdk2-cache-v1#OperationQuery", Response: "sdk2-cache-v1#MutationReceipt", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpCacheDiagnostics, Method: "GET", Path: "/api/cache/bindings/:id/diagnostics", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-v1", Kind: "read", SSE: false, Query: []string{"protocol", "after", "limit"}, Request: "sdk2-cache-v1#DiagnosticQuery", Response: "sdk2-cache-v1#DiagnosticPage", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpCacheCoreDiagnostics, Method: "GET", Path: "/api/cache/core/v1/bindings/:id/diagnostics", Params: []string{"id"}, Aliases: nil, Domain: "cache", Family: "sdk2-cache-core-v1", Kind: "read", SSE: false, Query: []string{"protocol", "limit", "after"}, Request: "", Response: "sdk2-cache-core-v1#Diagnostics", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalCapabilities, Method: "GET", Path: "/api/capabilities/terminal", Params: nil, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract"}, Request: "", Response: "terminal-services-v1#CapabilitiesResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalBindingCreate, Method: "POST", Path: "/api/terminal/bindings", Params: nil, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "write", SSE: false, Query: nil, Request: "terminal-services-v1#BindingRequest", Response: "terminal-services-v1#BindingResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalExecutorEventsObserve, Method: "GET", Path: "/api/terminal/executors/:id/events", Params: []string{"id"}, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "stream", SSE: true, Query: []string{"contract", "sessionContract", "connectionId"}, Request: "", Response: "terminal-services-v1#ExecutorEvent", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalOutputBatch, Method: "POST", Path: "/api/terminal/executors/:id/output-batches", Params: []string{"id"}, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "write", SSE: false, Query: nil, Request: "terminal-services-v1#OutputBatchRequest", Response: "terminal-services-v1#OutputStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalExecutionState, Method: "GET", Path: "/api/terminal/executors/:id/operations/:targetId", Params: []string{"id", "targetId"}, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract", "sessionId", "requestDigest", "connectionId"}, Request: "", Response: "terminal-services-v1#ExecutionState", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalOutputObserve, Method: "GET", Path: "/api/terminal/sessions/:id/tool-output", Params: []string{"id"}, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "stream", SSE: true, Query: []string{"contract", "sessionContract", "operationId", "requestDigest", "afterSeq"}, Request: "", Response: "terminal-services-v1#OutputEvent", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalOutputStatus, Method: "GET", Path: "/api/terminal/sessions/:id/tool-output-status", Params: []string{"id"}, Aliases: nil, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract", "operationId", "requestDigest"}, Request: "", Response: "terminal-services-v1#OutputStatus", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalConfigurationRead, Method: "GET", Path: "/api/terminal/sessions/:id/configuration", Params: []string{"id"}, Aliases: []string{"/api/sessions/:id/configuration"}, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract"}, Request: "", Response: "terminal-services-v1#ConfigurationResponse", ETagPath: []string{"configuration", "revision"}, ExpectedRevision: nil},
	{Name: OpTerminalConfigurationCommit, Method: "POST", Path: "/api/terminal/sessions/:id/configuration", Params: []string{"id"}, Aliases: []string{"/api/sessions/:id/configuration"}, Domain: "terminal", Family: "terminal-services-v1", Kind: "write", SSE: false, Query: nil, Request: "terminal-services-v1#ConfigurationRequest", Response: "terminal-services-v1#ConfigurationCommitResponse", ETagPath: []string{"configuration", "revision"}, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "integer"}},
	{Name: OpTerminalMemoryRead, Method: "GET", Path: "/api/terminal/sessions/:id/memory", Params: []string{"id"}, Aliases: []string{"/api/sessions/:id/memory"}, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract"}, Request: "", Response: "terminal-services-v1#MemoryStateResponse", ETagPath: []string{"memory", "revision"}, ExpectedRevision: nil},
	{Name: OpTerminalMemoryCommand, Method: "POST", Path: "/api/terminal/sessions/:id/memory/commands", Params: []string{"id"}, Aliases: []string{"/api/sessions/:id/memory/commands"}, Domain: "terminal", Family: "terminal-services-v1", Kind: "write", SSE: false, Query: nil, Request: "terminal-services-v1#MemoryCommandRequest", Response: "terminal-services-v1#MemoryReceiptResponse", ETagPath: nil, ExpectedRevision: &ExpectedRevision{Path: []string{"expectedRevision"}, Kind: "sequence"}},
	{Name: OpTerminalMemoryReceipt, Method: "GET", Path: "/api/terminal/sessions/:id/memory/commands/:targetId", Params: []string{"id", "targetId"}, Aliases: []string{"/api/sessions/:id/memory/commands/:targetId"}, Domain: "terminal", Family: "terminal-services-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract", "requestId"}, Request: "", Response: "terminal-services-v1#MemoryReceiptResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalObservationResources, Method: "GET", Path: "/api/terminal/observation/sessions/:id/resources", Params: []string{"id"}, Aliases: nil, Domain: "terminal-observation", Family: "terminal-observation-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract"}, Request: "", Response: "terminal-observation-v1#ResourcesResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalObservationCorrelations, Method: "GET", Path: "/api/terminal/observation/sessions/:id/output-correlations", Params: []string{"id"}, Aliases: nil, Domain: "terminal-observation", Family: "terminal-observation-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract", "toolCallId"}, Request: "", Response: "terminal-observation-v1#CorrelationsResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalProfileCatalog, Method: "GET", Path: "/api/terminal/profile/sessions/:id/catalog", Params: []string{"id"}, Aliases: nil, Domain: "terminal-profile", Family: "terminal-profile-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract"}, Request: "", Response: "terminal-profile-v1#CatalogResponse", ETagPath: nil, ExpectedRevision: nil},
	{Name: OpTerminalProfileUsage, Method: "GET", Path: "/api/terminal/profile/sessions/:id/usage", Params: []string{"id"}, Aliases: nil, Domain: "terminal-profile", Family: "terminal-profile-v1", Kind: "read", SSE: false, Query: []string{"contract", "sessionContract"}, Request: "", Response: "terminal-profile-v1#UsageResponse", ETagPath: nil, ExpectedRevision: nil},
}
